import type { Subject, Topic } from "@/types/subject";

/**
 * ⚠️ id (std6, ch1, ch2, set1…) ક્યારેય બદલવા નહીં —
 * વિદ્યાર્થીની localStorage માં સચવાયેલી progress તૂટે.
 */
export const subjects: Subject[] = [
  {
    id: "std6",
    name: "ધોરણ 6",
    icon: "🔬",
    topicCount: 12,
    questionCount: 480,
    color: "#06b6d4",
    color2: "#7c3aed",
    description: "સંપૂર્ણ ધોરણ ૬ વિજ્ઞાન પાઠ્યપુસ્તક (પ્રકરણ ૧ થી ૧૨)",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "આહારના ઘટકો",
        fullTitle: "પ્રકરણ 1 — આહારના ઘટકો",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/ધોરણ 6/1 - આહારના ઘટકો.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "વસ્તુઓના જૂથ બનાવવાં",
        fullTitle: "પ્રકરણ 2 — વસ્તુઓના જૂથ બનાવવાં",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/2 - વસ્તુઓના જૂથ બનાવવાં.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "પદાર્થોનું અલગીકરણ",
        fullTitle: "પ્રકરણ 3 — પદાર્થોનું અલગીકરણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/3 - પદાર્થોનું અલગીકરણ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "વનસ્પતિની જાણકારી મેળવીએ",
        fullTitle: "પ્રકરણ 4 — વનસ્પતિની જાણકારી મેળવીએ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/4 - વનસ્પતિની જાણકારી મેળવીએ.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "શરીરનું હલનચલન",
        fullTitle: "પ્રકરણ 5 — શરીરનું હલનચલન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/5 - શરીરનું હલનચલન.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "સજીવો – લક્ષણો અને નિવાસસ્થાન",
        fullTitle: "પ્રકરણ 6 — સજીવો – લક્ષણો અને નિવાસસ્થાન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/6 - સજીવો  લક્ષણો અને નિવા ાસસ્થાન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "ગતિ અને અંતરનું માપન",
        fullTitle: "પ્રકરણ 7 — ગતિ અને અંતરનું માપન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/7 - ગતિ અને અંતરનું માપન.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "પ્રકાશ, પડછાયો અને પરાવર્તન",
        fullTitle: "પ્રકરણ 8 — પ્રકાશ, પડછાયો અને પરાવર્તન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/8 - પ્રકાશ પડછાયો અને પરાવર્તતતન.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "વિદ્યુત તથા પરિપથ",
        fullTitle: "પ્રકરણ 9 — વિદ્યુત તથા પરિપથ",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 6/9 - વિદ્યુત તથા પરિપથ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "ચુંબક સાથે ગમ્મત",
        fullTitle: "પ્રકરણ 10 — ચુંબક સાથે ગમ્મત",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/10 - ચુંબક સાથે ગમ્મત.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "આપણી આસપાસની હવા",
        fullTitle: "પ્રકરણ 11 — આપણી આસપાસની હવા",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 6/11 - આપણી આસપાસની હવા.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 12 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 6/12 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std7",
    name: "ધોરણ 7",
    icon: "🌱",
    topicCount: 14,
    questionCount: 475,
    color: "#10b981",
    color2: "#059669",
    description: "સંપૂર્ણ ધોરણ ૭ વિજ્ઞાન પાઠ્યપુસ્તક (પ્રકરણ ૧ થી ૧૪)",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "વનસ્પતિમાં પોષણ",
        fullTitle: "પ્રકરણ 1 — વનસ્પતિમાં પોષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/1 - વનસ્પતિમાં પોષણ.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "પ્રાણીઓમાં પોષણ",
        fullTitle: "પ્રકરણ 2 — પ્રાણીઓમાં પોષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/2 - પ્રાણીઓમાં પોષણ.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "ઉષ્મા",
        fullTitle: "પ્રકરણ 3 — ઉષ્મા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/3 - ઉષ્મા.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "એસિડ, બેઇઝ અને ક્ષાર",
        fullTitle: "પ્રકરણ 4 — એસિડ, બેઇઝ અને ક્ષાર",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/4 - એસિડ બેઇઝ અને ક્ષાર.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "ભૌતિક અને રાસાયણિક ફેરફારો",
        fullTitle: "પ્રકરણ 5 — ભૌતિક અને રાસાયણિક ફેરફારો",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 7/5 - ભૌતિક અને રાસાયણિક ફેરફારો.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "સજીવોમાં શ્વસન",
        fullTitle: "પ્રકરણ 6 — સજીવોમાં શ્વસન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/6 - સજીવોમાં શ્વસન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "પ્રાણીઓ અને વનસ્પતિઓમાં વહન",
        fullTitle: "પ્રકરણ 7 — પ્રાણીઓ અને વનસ્પતિઓમાં વહન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/7 - પ્રાણીઓ અને વનસ્પતિઓમાં વહન.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "વનસ્પતિઓમાં પ્રજનન",
        fullTitle: "પ્રકરણ 8 — વનસ્પતિઓમાં પ્રજનન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/8 - વનસ્પતિઓમાં પ્રજનન.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "ગતિ અને સમય",
        fullTitle: "પ્રકરણ 9 — ગતિ અને સમય",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/9 - ગતિ અને સમય.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "વિદ્યુતપ્રવાહ અને તેની અસરો",
        fullTitle: "પ્રકરણ 10 — વિદ્યુતપ્રવાહ અને તેની અસરો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/10 - વિદ્યુતપ્રવાહ અને તેની અસરો.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "પ્રકાશ",
        fullTitle: "પ્રકરણ 11 — પ્રકાશ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/11 - પ્રકાશ.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "જંગલો આપણી જીવાદોરી",
        fullTitle: "પ્રકરણ 12 — જંગલો આપણી જીવાદોરી",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 7/12 - જંગલો આપણી ી જીવાદોરી.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "દૂષિત પાણીની વાર્તા",
        fullTitle: "પ્રકરણ 13 — દૂષિત પાણીની વાર્તા",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 7/13 - દુષિત પાણીની વાર્તા.pdf",
      },
      {
        id: "ch14",
        number: "14",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 14 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 7/14 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std8",
    name: "ધોરણ 8",
    icon: "🌾",
    topicCount: 14,
    questionCount: 570,
    color: "#16a34a",
    color2: "#059669",
    description: "સંપૂર્ણ ધોરણ ૮ વિજ્ઞાન પાઠ્યપુસ્તક (પ્રકરણ ૧ થી ૧૪)",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "પાક ઉત્પાદન અને વ્યવસ્થાપન",
        fullTitle: "પ્રકરણ 1 — પાક ઉત્પાદન અને વ્યવસ્થાપન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/1 - પાક ઉત્પાદન અને વ્યવસ્થાપન.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "સુક્ષ્મજીવો મિત્ર અને શત્રુ",
        fullTitle: "પ્રકરણ 2 — સુક્ષ્મજીવો મિત્ર અને શત્રુ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/2 - સુક્ષ્મજીવો મિત્ર અને શત્રુ.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "કોલસો અને પેટ્રોલિયમ",
        fullTitle: "પ્રકરણ 3 — કોલસો અને પેટ્રોલિયમ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/3 - કોલસો અને પેટ્રોલિયમ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "દહન અને જ્યોત",
        fullTitle: "પ્રકરણ 4 — દહન અને જ્યોત",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/4 - દહન અને જ્યોત.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "વનસ્પતિઓ અને પ્રાણીઓનું સંરક્ષણ",
        fullTitle: "પ્રકરણ 5 — વનસ્પતિઓ અને પ્રાણીઓનું સંરક્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/5 - વનસ્પતિઓ અને પ્રાણીઓનું સંરક્ષણ.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "પ્રાણીઓમાં પ્રજનન",
        fullTitle: "પ્રકરણ 6 — પ્રાણીઓમાં પ્રજનન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/6 - પ્રણીઓમાં પ્રજનન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "કિશોરાવસ્થા તરફ",
        fullTitle: "પ્રકરણ 7 — કિશોરાવસ્થા તરફ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/7 - કિશોરાવસ્થા તરફ.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "બળ અને દબાણ",
        fullTitle: "પ્રકરણ 8 — બળ અને દબાણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/8 - બળ અને દબાણ.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "ઘર્ષણ",
        fullTitle: "પ્રકરણ 9 — ઘર્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/9 - ઘર્ષષણ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "ધ્વનિ",
        fullTitle: "પ્રકરણ 10 — ધ્વનિ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/10 - ધ્વનિ.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "વિદ્યુતપ્રવાહની રાસાયણિક અસરો",
        fullTitle: "પ્રકરણ 11 — વિદ્યુતપ્રવાહની રાસાયણિક અસરો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/11 - વિદ્યુતપ્રવાહની રાસાયણિક અસરો.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "કેટલીક કુદરતી ઘટનાઓ",
        fullTitle: "પ્રકરણ 12 — કેટલીક કુદરતી ઘટનાઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/12 - કેટલીક કુદરતી ઘટનાઓ.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "પ્રકાશ",
        fullTitle: "પ્રકરણ 13 — પ્રકાશ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/13 - પ્રકાશ.pdf",
      },
      {
        id: "ch14",
        number: "14",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 14 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 8/14 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std9",
    name: "ધોરણ 9",
    icon: "🧪",
    topicCount: 13,
    questionCount: 460,
    color: "#3b82f6",
    color2: "#1d4ed8",
    description: "સંપૂર્ણ ધોરણ ૯ વિજ્ઞાન પાઠ્યપુસ્તક (પ્રકરણ ૧ થી ૧૩)",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "આપણી આસપાસમાં દ્રવ્ય",
        fullTitle: "પ્રકરણ 1 — આપણી આસપાસમાં દ્રવ્ય",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/1 - આપણી ી આસપાસમાં દ્રવ્ય.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "આપણી આસપાસના દ્રવ્યો શુદ્ધ છે?",
        fullTitle: "પ્રકરણ 2 — આપણી આસપાસના દ્રવ્યો શુદ્ધ છે?",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/2 - આપણી ી આસપાસના દ્રવ્યો શુદ્ધ છે.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "પરમાણુ અને અણુઓ",
        fullTitle: "પ્રકરણ 3 — પરમાણુ અને અણુઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/3 - પરમાણુ અને અણુઓ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "પરમાણુનું બંધારણ",
        fullTitle: "પ્રકરણ 4 — પરમાણુનું બંધારણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/4 - પરમાણુનું બંધારણ.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "સજીવનો પાયાનો એકમ",
        fullTitle: "પ્રકરણ 5 — સજીવનો પાયાનો એકમ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/5 - સજીવનો પાયાનો એકમ.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "પેશીઓ",
        fullTitle: "પ્રકરણ 6 — પેશીઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/6 - પેશીઓ.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "ગતિ",
        fullTitle: "પ્રકરણ 7 — ગતિ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/7 - ગતિ.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "બળ અને ગતિના નિયમો",
        fullTitle: "પ્રકરણ 8 — બળ અને ગતિના નિયમો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/8 - બળ અને ગતિના નિયમો.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "ગુરુત્વાકર્ષણ",
        fullTitle: "પ્રકરણ 9 — ગુરુત્વાકર્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/9 - ગુરુત્વાકર્ષષણ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "કાર્ય અને ઊર્જા",
        fullTitle: "પ્રકરણ 10 — કાર્ય અને ઊર્જા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/10 - કાર્યય અને ઊર્જા.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "ધ્વનિ",
        fullTitle: "પ્રકરણ 11 — ધ્વનિ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/11 - ધ્વનિ.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "અન્નસ્ત્રોતોમાં સુધારણા",
        fullTitle: "પ્રકરણ 12 — અન્નસ્ત્રોતોમાં સુધારણા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/12 - અન્નસ્ત્રોતોમાં સુધારણા.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 13 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 9/13 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
];

export function getSubject(subjectId: string): Subject | undefined {
  return subjects.find((s) => s.id === subjectId);
}

export function getTopic(
  subjectId: string,
  topicId: string,
): { subject: Subject; topic: Topic } | undefined {
  const subject = getSubject(subjectId);
  const topic = subject?.topics.find((t) => t.id === topicId);
  if (!subject || !topic) return undefined;
  return { subject, topic };
}

export const siteStats = {
  subjects: subjects.length,
  chapters: subjects.reduce((n, s) => n + s.topicCount, 0),
  questions: subjects.reduce((n, s) => n + s.questionCount, 0),
};
