import type { Subject, Topic } from "@/types/subject";

/**
 * ⚠️ id (std6, ch1, ch2, set1…) ક્યારેય બદલવા નહીં —
 * વિદ્યાર્થીની localStorage માં સચવાયેલી progress તૂટે.
 */
export const subjects: Subject[] = [
  {
    id: "std6",
    name: "ધોરણ 6",
    icon: "🔬",
    topicCount: 12,
    questionCount: 480,
    color: "#06b6d4",
    color2: "#7c3aed",
    description: "સંપૂર્ણ ધોરણ ૬ વિજ્ઞાન પાઠ્યપુસ્તક",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "આહારના ઘટકો",
        fullTitle: "પ્રકરણ 1 — આહારના ઘટકો",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/ધોરણ 6/1 - આહારના ઘટકો.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "વસ્તુઓના જૂથ બનાવવાં",
        fullTitle: "પ્રકરણ 2 — વસ્તુઓના જૂથ બનાવવાં",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/2 - વસ્તુઓના જૂથ બનાવવાં.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "પદાર્થોનું અલગીકરણ",
        fullTitle: "પ્રકરણ 3 — પદાર્થોનું અલગીકરણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/3 - પદાર્થોનું અલગીકરણ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "વનસ્પતિની જાણકારી મેળવીએ",
        fullTitle: "પ્રકરણ 4 — વનસ્પતિની જાણકારી મેળવીએ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/4 - વનસ્પતિની જાણકારી મેળવીએ.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "શરીરનું હલનચલન",
        fullTitle: "પ્રકરણ 5 — શરીરનું હલનચલન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/5 - શરીરનું હલનચલન.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "સજીવો – લક્ષણો અને નિવાસસ્થાન",
        fullTitle: "પ્રકરણ 6 — સજીવો – લક્ષણો અને નિવાસસ્થાન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/6 - સજીવો  લક્ષણો અને નિવા ાસસ્થાન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "ગતિ અને અંતરનું માપન",
        fullTitle: "પ્રકરણ 7 — ગતિ અને અંતરનું માપન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/7 - ગતિ અને અંતરનું માપન.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "પ્રકાશ, પડછાયો અને પરાવર્તન",
        fullTitle: "પ્રકરણ 8 — પ્રકાશ, પડછાયો અને પરાવર્તન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/8 - પ્રકાશ પડછાયો અને પરાવર્તતતન.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "વિદ્યુત તથા પરિપથ",
        fullTitle: "પ્રકરણ 9 — વિદ્યુત તથા પરિપથ",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 6/9 - વિદ્યુત તથા પરિપથ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "ચુંબક સાથે ગમ્મત",
        fullTitle: "પ્રકરણ 10 — ચુંબક સાથે ગમ્મત",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 6/10 - ચુંબક સાથે ગમ્મત.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "આપણી આસપાસની હવા",
        fullTitle: "પ્રકરણ 11 — આપણી આસપાસની હવા",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 6/11 - આપણી આસપાસની હવા.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 12 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 6/12 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std7",
    name: "ધોરણ 7",
    icon: "🌱",
    topicCount: 14,
    questionCount: 475,
    color: "#10b981",
    color2: "#059669",
    description: "સંપૂર્ણ ધોરણ ૭ વિજ્ઞાન પાઠ્યપુસ્તક",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "વનસ્પતિમાં પોષણ",
        fullTitle: "પ્રકરણ 1 — વનસ્પતિમાં પોષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/1 - વનસ્પતિમાં પોષણ.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "પ્રાણીઓમાં પોષણ",
        fullTitle: "પ્રકરણ 2 — પ્રાણીઓમાં પોષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/2 - પ્રાણીઓમાં પોષણ.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "ઉષ્મા",
        fullTitle: "પ્રકરણ 3 — ઉષ્મા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/3 - ઉષ્મા.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "એસિડ, બેઇઝ અને ક્ષાર",
        fullTitle: "પ્રકરણ 4 — એસિડ, બેઇઝ અને ક્ષાર",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/4 - એસિડ બેઇઝ અને ક્ષાર.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "ભૌતિક અને રાસાયણિક ફેરફારો",
        fullTitle: "પ્રકરણ 5 — ભૌતિક અને રાસાયણિક ફેરફારો",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 7/5 - ભૌતિક અને રાસાયણિક ફેરફારો.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "સજીવોમાં શ્વસન",
        fullTitle: "પ્રકરણ 6 — સજીવોમાં શ્વસન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/6 - સજીવોમાં શ્વસન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "પ્રાણીઓ અને વનસ્પતિઓમાં વહન",
        fullTitle: "પ્રકરણ 7 — પ્રાણીઓ અને વનસ્પતિઓમાં વહન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/7 - પ્રાણીઓ અને વનસ્પતિઓમાં વહન.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "વનસ્પતિઓમાં પ્રજનન",
        fullTitle: "પ્રકરણ 8 — વનસ્પતિઓમાં પ્રજનન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/8 - વનસ્પતિઓમાં પ્રજનન.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "ગતિ અને સમય",
        fullTitle: "પ્રકરણ 9 — ગતિ અને સમય",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/9 - ગતિ અને સમય.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "વિદ્યુતપ્રવાહ અને તેની અસરો",
        fullTitle: "પ્રકરણ 10 — વિદ્યુતપ્રવાહ અને તેની અસરો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/10 - વિદ્યુતપ્રવાહ અને તેની અસરો.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "પ્રકાશ",
        fullTitle: "પ્રકરણ 11 — પ્રકાશ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 7/11 - પ્રકાશ.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "જંગલો આપણી જીવાદોરી",
        fullTitle: "પ્રકરણ 12 — જંગલો આપણી જીવાદોરી",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 7/12 - જંગલો આપણી ી જીવાદોરી.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "દૂષિત પાણીની વાર્તા",
        fullTitle: "પ્રકરણ 13 — દૂષિત પાણીની વાર્તા",
        hasTheory: true,
        hasTest: true,
        testSets: 1,
        pdfUrl: "/pdfs/ધોરણ 7/13 - દુષિત પાણીની વાર્તા.pdf",
      },
      {
        id: "ch14",
        number: "14",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 14 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 7/14 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std8",
    name: "ધોરણ 8",
    icon: "🌾",
    topicCount: 14,
    questionCount: 570,
    color: "#16a34a",
    color2: "#059669",
    description: "સંપૂર્ણ ધોરણ ૮ વિજ્ઞાન પાઠ્યપુસ્તક",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "પાક ઉત્પાદન અને વ્યવસ્થાપન",
        fullTitle: "પ્રકરણ 1 — પાક ઉત્પાદન અને વ્યવસ્થાપન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/1 - પાક ઉત્પાદન અને વ્યવસ્થાપન.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "સુક્ષ્મજીવો મિત્ર અને શત્રુ",
        fullTitle: "પ્રકરણ 2 — સુક્ષ્મજીવો મિત્ર અને શત્રુ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/2 - સુક્ષ્મજીવો મિત્ર અને શત્રુ.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "કોલસો અને પેટ્રોલિયમ",
        fullTitle: "પ્રકરણ 3 — કોલસો અને પેટ્રોલિયમ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/3 - કોલસો અને પેટ્રોલિયમ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "દહન અને જ્યોત",
        fullTitle: "પ્રકરણ 4 — દહન અને જ્યોત",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/4 - દહન અને જ્યોત.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "વનસ્પતિઓ અને પ્રાણીઓનું સંરક્ષણ",
        fullTitle: "પ્રકરણ 5 — વનસ્પતિઓ અને પ્રાણીઓનું સંરક્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/5 - વનસ્પતિઓ અને પ્રાણીઓનું સંરક્ષણ.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "પ્રાણીઓમાં પ્રજનન",
        fullTitle: "પ્રકરણ 6 — પ્રાણીઓમાં પ્રજનન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/6 - પ્રણીઓમાં પ્રજનન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "કિશોરાવસ્થા તરફ",
        fullTitle: "પ્રકરણ 7 — કિશોરાવસ્થા તરફ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/7 - કિશોરાવસ્થા તરફ.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "બળ અને દબાણ",
        fullTitle: "પ્રકરણ 8 — બળ અને દબાણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/8 - બળ અને દબાણ.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "ઘર્ષણ",
        fullTitle: "પ્રકરણ 9 — ઘર્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/9 - ઘર્ષષણ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "ધ્વનિ",
        fullTitle: "પ્રકરણ 10 — ધ્વનિ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/10 - ધ્વનિ.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "વિદ્યુતપ્રવાહની રાસાયણિક અસરો",
        fullTitle: "પ્રકરણ 11 — વિદ્યુતપ્રવાહની રાસાયણિક અસરો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/11 - વિદ્યુતપ્રવાહની રાસાયણિક અસરો.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "કેટલીક કુદરતી ઘટનાઓ",
        fullTitle: "પ્રકરણ 12 — કેટલીક કુદરતી ઘટનાઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/12 - કેટલીક કુદરતી ઘટનાઓ.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "પ્રકાશ",
        fullTitle: "પ્રકરણ 13 — પ્રકાશ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 8/13 - પ્રકાશ.pdf",
      },
      {
        id: "ch14",
        number: "14",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 14 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 8/14 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std9",
    name: "ધોરણ 9",
    icon: "🧪",
    topicCount: 13,
    questionCount: 460,
    color: "#3b82f6",
    color2: "#1d4ed8",
    description: "સંપૂર્ણ ધોરણ ૯ વિજ્ઞાન પાઠ્યપુસ્તક",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "આપણી આસપાસમાં દ્રવ્ય",
        fullTitle: "પ્રકરણ 1 — આપણી આસપાસમાં દ્રવ્ય",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/1 - આપણી ી આસપાસમાં દ્રવ્ય.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "આપણી આસપાસના દ્રવ્યો શુદ્ધ છે?",
        fullTitle: "પ્રકરણ 2 — આપણી આસપાસના દ્રવ્યો શુદ્ધ છે?",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/2 - આપણી ી આસપાસના દ્રવ્યો શુદ્ધ છે.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "પરમાણુ અને અણુઓ",
        fullTitle: "પ્રકરણ 3 — પરમાણુ અને અણુઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/3 - પરમાણુ અને અણુઓ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "પરમાણુનું બંધારણ",
        fullTitle: "પ્રકરણ 4 — પરમાણુનું બંધારણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/4 - પરમાણુનું બંધારણ.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "સજીવનો પાયાનો એકમ",
        fullTitle: "પ્રકરણ 5 — સજીવનો પાયાનો એકમ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/5 - સજીવનો પાયાનો એકમ.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "પેશીઓ",
        fullTitle: "પ્રકરણ 6 — પેશીઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/6 - પેશીઓ.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "ગતિ",
        fullTitle: "પ્રકરણ 7 — ગતિ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/7 - ગતિ.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "બળ અને ગતિના નિયમો",
        fullTitle: "પ્રકરણ 8 — બળ અને ગતિના નિયમો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/8 - બળ અને ગતિના નિયમો.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "ગુરુત્વાકર્ષણ",
        fullTitle: "પ્રકરણ 9 — ગુરુત્વાકર્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/9 - ગુરુત્વાકર્ષષણ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "કાર્ય અને ઊર્જા",
        fullTitle: "પ્રકરણ 10 — કાર્ય અને ઊર્જા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/10 - કાર્યય અને ઊર્જા.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "ધ્વનિ",
        fullTitle: "પ્રકરણ 11 — ધ્વનિ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/11 - ધ્વનિ.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "અન્નસ્ત્રોતોમાં સુધારણા",
        fullTitle: "પ્રકરણ 12 — અન્નસ્ત્રોતોમાં સુધારણા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 9/12 - અન્નસ્ત્રોતોમાં સુધારણા.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 13 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 9/13 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "std10",
    name: "ધોરણ 10",
    icon: "🔬",
    topicCount: 14,
    questionCount: 490,
    color: "#059669",
    color2: "#0284c7",
    description: "સંપૂર્ણ ધોરણ ૧૦ વિજ્ઞાન પાઠ્યપુસ્તક",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "રાસાયણિક પ્રક્રિયાઓ અને સમીકરણો",
        fullTitle: "પ્રકરણ 1 — રાસાયણિક પ્રક્રિયાઓ અને સમીકરણો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/1 - રાસાયણિક પ્રક્રિયાઓ અને સમીકરણો.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "એસિડ, બેઈઝ અને ક્ષાર",
        fullTitle: "પ્રકરણ 2 — એસિડ, બેઈઝ અને ક્ષાર",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/2 - એસિડ બેઈઝ અને ક્ષાર.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "ધાતુઓ અને અધાતુઓ",
        fullTitle: "પ્રકરણ 3 — ધાતુઓ અને અધાતુઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/3 - ધાતુઓ અને અધાતુઓ.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "કાર્બન અને તેના સંયોજનો",
        fullTitle: "પ્રકરણ 4 — કાર્બન અને તેના સંયોજનો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/4 - કાર્બબન અને તેના સંયોજનો.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "જૈવિક ક્રિયાઓ",
        fullTitle: "પ્રકરણ 5 — જૈવિક ક્રિયાઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/5 - જૈવિક ક્રિયાઓ.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "નિયંત્રણ અને સંકલન",
        fullTitle: "પ્રકરણ 6 — નિયંત્રણ અને સંકલન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/6 - નિયં ત્રણ અને સંકલન.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "સજીવો કેવી રીતે પ્રજનન કરે છે?",
        fullTitle: "પ્રકરણ 7 — સજીવો કેવી રીતે પ્રજનન કરે છે?",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/7 - સજીવો કેવી રીતે પ્રજજન કરે છે.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "આનુવંશિકતા",
        fullTitle: "પ્રકરણ 8 — આનુવંશિકતા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/8 - આનુવંશિકતા.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "પ્રકાશ - પરાવર્તન અને વક્રીભવન",
        fullTitle: "પ્રકરણ 9 — પ્રકાશ - પરાવર્તન અને વક્રીભવન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/9 - પ્રકાશ પરાવર્તતતન અને વક્રીભવન.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "માનવ આંખ અને રંગબેરંગી દુનિયા",
        fullTitle: "પ્રકરણ 10 — માનવ આંખ અને રંગબેરંગી દુનિયા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/10 - માનવ આંખ અને રંગબેરંગી દુનિયા ા.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "વિદ્યુત",
        fullTitle: "પ્રકરણ 11 — વિદ્યુત",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/11 - વિદ્યુત.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "વિદ્યુત પ્રવાહની ચુંબકીય અસરો",
        fullTitle: "પ્રકરણ 12 — વિદ્યુત પ્રવાહની ચુંબકીય અસરો",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/12 - વિદ્યુત પ્રવાહની ચું બકીય અસરો.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "આપણું પર્યાવરણ",
        fullTitle: "પ્રકરણ 13 — આપણું પર્યાવરણ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/ધોરણ 10/13 - આપણું પર્યાવરણ.pdf",
      },
      {
        id: "ch14",
        number: "14",
        title: "મેગા ટેસ્ટ (સંપૂર્ણ પુનરાવર્તન)",
        fullTitle: "પ્રકરણ 14 — મેગા ટેસ્ટ (૧૦૦ પ્રશ્નો)",
        hasTheory: true,
        hasTest: true,
        testSets: 5,
        pdfUrl: "/pdfs/ધોરણ 10/14 - મેગા ટેસ્ટ.pdf",
      },
    ],
  },
  {
    id: "pedagogy",
    name: "વિજ્ઞાન પદ્ધતિશાસ્ત્ર",
    icon: "🎓",
    topicCount: 22,
    questionCount: 810,
    color: "#8b5cf6",
    color2: "#6d28d9",
    description: "વિજ્ઞાન પદ્ધતિશાસ્ત્ર પાઠ્યપુસ્તક",
    topics: [
      {
        id: "ch1",
        number: "1",
        title: "વિજ્ઞાનનું સ્વરૂપ અને માળખું",
        fullTitle: "પ્રકરણ 1 — વિજ્ઞાનનું સ્વરૂપ અને માળખું",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/1 - વિજ્ઞાનનું સ્વરૂપ અને માળખું.pdf",
      },
      {
        id: "ch2",
        number: "2",
        title: "કુદરતી વિજ્ઞાન ઉદ્દેશ્યો અને હેતુઓ",
        fullTitle: "પ્રકરણ 2 — કુદરતી વિજ્ઞાન ઉદ્દેશ્યો અને હેતુઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/2 - કુદરતી વિજ્ઞાન ઉદ્દેશ્યો અને હેતુઓ.pdf",
      },
      {
        id: "ch3",
        number: "3",
        title: "વિજ્ઞાનની સમજ અને કદર",
        fullTitle: "પ્રકરણ 3 — વિજ્ઞાનની સમજ અને કદર",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/3 - વિજ્ઞાનની સમજ અને કદર.pdf",
      },
      {
        id: "ch4",
        number: "4",
        title: "અભિગમો",
        fullTitle: "પ્રકરણ 4 — અભિગમો",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/4 - અભિગમો.pdf",
      },
      {
        id: "ch5",
        number: "5",
        title: "શિક્ષણ પદ્ધતિઓ",
        fullTitle: "પ્રકરણ 5 — શિક્ષણ પદ્ધતિઓ",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/5 - શિક્ષણ પદ્ધતિઓ.pdf",
      },
      {
        id: "ch6",
        number: "6",
        title: "વિજ્ઞાન શિક્ષણમાં અધ્યયન-અધ્યાપન સામગ્રી",
        fullTitle: "પ્રકરણ 6 — વિજ્ઞાન શિક્ષણમાં અધ્યયન-અધ્યાપન સામગ્રી",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/6 - વિજ્ઞાન શિક્ષણમાં અધ્યયન-અધ્યાપન સામગ્રી.pdf",
      },
      {
        id: "ch7",
        number: "7",
        title: "મૂલ્યાંકન",
        fullTitle: "પ્રકરણ 7 — મૂલ્યાંકન",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/7 - મૂલ્યાંકન.pdf",
      },
      {
        id: "ch8",
        number: "8",
        title: "નિદાનાત્મક-ઉપચારાત્મક શિક્ષણ",
        fullTitle: "પ્રકરણ 8 — નિદાનાત્મક-ઉપચારાત્મક શિક્ષણ",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/8 - નિદાનાત્મક-ઉપચારાત્મક શિક્ષણ.pdf",
      },
      {
        id: "ch9",
        number: "9",
        title: "વિજ્ઞાન શિક્ષણમાં નાવીન્યકરણ",
        fullTitle: "પ્રકરણ 9 — વિજ્ઞાન શિક્ષણમાં નાવીન્યકરણ",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/9 - વિજ્ઞાન શિક્ષણમાં નાવીન્યકરણ.pdf",
      },
      {
        id: "ch10",
        number: "10",
        title: "વિજ્ઞાન મંડળ",
        fullTitle: "પ્રકરણ 10 — વિજ્ઞાન મંડળ",
        hasTheory: true,
        hasTest: true,
        testSets: 3,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/10 - વિજ્ઞાન મંડળ.pdf",
      },
      {
        id: "ch11",
        number: "11",
        title: "ક્ષેત્રીય મુલાકાત",
        fullTitle: "પ્રકરણ 11 — ક્ષેત્રીય મુલાકાત",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/11 - ક્ષેત્રીય મુલાકાત.pdf",
      },
      {
        id: "ch12",
        number: "12",
        title: "વિજ્ઞાન પ્રયોગશાળા",
        fullTitle: "પ્રકરણ 12 — વિજ્ઞાન પ્રયોગશાળા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/12 - વિજ્ઞાન પ્રયોગશાળા.pdf",
      },
      {
        id: "ch13",
        number: "13",
        title: "અસરકારક વર્ગવ્યવહાર",
        fullTitle: "પ્રકરણ 13 — અસરકારક વર્ગવ્યવહાર",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/13 - અસરકારક વર્ગગવ્યવહાર.pdf",
      },
      {
        id: "ch14",
        number: "14",
        title: "માઇક્રોટીચિંગ સૂક્ષ્મ અધ્યાપન",
        fullTitle: "પ્રકરણ 14 — માઇક્રોટીચિંગ સૂક્ષ્મ અધ્યાપન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/14 - માઇક્રોટીચિંગ સૂક્ષ્મ અધ્યાપન.pdf",
      },
      {
        id: "ch15",
        number: "15",
        title: "સિમ્યુલેશન આભાસી અધ્યાપન",
        fullTitle: "પ્રકરણ 15 — સિમ્યુલેશન આભાસી અધ્યાપન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/15 - સિમ્યુલેશન  આભાસી અધ્યાપન.pdf",
      },
      {
        id: "ch16",
        number: "16",
        title: "શિક્ષણમાં માહિતી અને પ્રત્યાયન પ્રૌદ્યોગિકી ICT",
        fullTitle: "પ્રકરણ 16 — શિક્ષણમાં માહિતી અને પ્રત્યાયન પ્રૌદ્યોગિકી ICT",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/16 - શિક્ષણમાં માહિતી અને પ્રત્યાયન પ્રૌદ્યોગિકી ICT.pdf",
      },
      {
        id: "ch17",
        number: "17",
        title: "સરકારી ડિજિટલ શિક્ષણ પહેલ",
        fullTitle: "પ્રકરણ 17 — સરકારી ડિજિટલ શિક્ષણ પહેલ",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/17 - સરકારી ડિજિટલ શિક્ષણ પહેલ.pdf",
      },
      {
        id: "ch18",
        number: "18",
        title: "અધ્યાપનનાં સૂત્રો – સંપૂર્ણ માર્ગદર્શિકા",
        fullTitle: "પ્રકરણ 18 — અધ્યાપનનાં સૂત્રો – સંપૂર્ણ માર્ગદર્શિકા",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/18 - અધ્યાપનનાં સૂત્રો   સંપૂર્ણણ માર્ગગદર્શિકા.pdf",
      },
      {
        id: "ch19",
        number: "19",
        title: "શૈક્ષણિક આયોજન",
        fullTitle: "પ્રકરણ 19 — શૈક્ષણિક આયોજન",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/19 - શૈક્ષણિક આયોજન.pdf",
      },
      {
        id: "ch20",
        number: "20",
        title: "માહિતી અધિકાર અધિનિયમ RTI Act ૨૦૦૫",
        fullTitle: "પ્રકરણ 20 — માહિતી અધિકાર અધિનિયમ RTI Act ૨૦૦૫",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/20 - માહિતી અધિકાર અધિનિ યમ RTI Act ૨૦૦૫.pdf",
      },
      {
        id: "ch21",
        number: "21",
        title: "બાળકોને મફત અને ફરજિયાત શિક્ષણનો અધિકાર અધિનિયમ RTE Act 2009",
        fullTitle: "પ્રકરણ 21 — બાળકોને મફત અને ફરજિયાત શિક્ષણનો અધિકાર અધિનિયમ RTE Act 2009",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/21 - બાળકોને મફત અને ફરજિયાત શિક્ષણનો અધિકાર અધિનિ યમ - ૨૦૦૯ RTE Act 2009.pdf",
      },
      {
        id: "ch22",
        number: "22",
        title: "રાષ્ટ્રીય શિક્ષણ નીતિ NEP 2020",
        fullTitle: "પ્રકરણ 22 — રાષ્ટ્રીય શિક્ષણ નીતિ NEP 2020",
        hasTheory: true,
        hasTest: true,
        testSets: 2,
        pdfUrl: "/pdfs/વિજ્ઞાન પદ્ધતિશાસ્ત્ર/22 - રાષ્ટ્રીય શિક્ષણ નીતિ NEP 2020 માસ્ટર ફાઇલ.pdf",
      },
    ],
  },
];

export function getSubject(subjectId: string): Subject | undefined {
  return subjects.find((s) => s.id === subjectId);
}

export function getTopic(
  subjectId: string,
  topicId: string,
): { subject: Subject; topic: Topic } | undefined {
  const subject = getSubject(subjectId);
  const topic = subject?.topics.find((t) => t.id === topicId);
  if (!subject || !topic) return undefined;
  return { subject, topic };
}

export const siteStats = {
  subjects: subjects.length,
  chapters: subjects.reduce((n, s) => n + s.topicCount, 0),
  questions: subjects.reduce((n, s) => n + s.questionCount, 0),
};
